services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch1
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9010:9010"
      - "9181:9181"
      - "9009:9009"
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: "1"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
